version: '2'
services:
  devpostgre:
    image: postgres
    container_name: dev-postgre
    logging:
       options:
         max-size: "50m"
    volumes:
      - ./data/postgre:/pgdata
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=TestPassword
      - PGDATA=/pgdata
  devtomcat:
    image: tomcat
    container_name: dev-tomcat
    logging:
       options:
         max-size: "50m"
    links:
      - devpostgre:postgre_host
    volumes:
      - ./data/tomcat:/usr/local/tomcat/webapps
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://postgre_host:5432/engineroomdb
  devnginx:
    image: nginx
    container_name: dev-nginx
    logging:
      options:
        max-size: "50m"
    links:
      - devtomcat:dev_tomcat
    volumes:
      - ./data/web:/usr/share/nginx/html:ro
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
